name: CI
on:
  push:
jobs:
  "Linux_Latest":
    uses: "projectsynchro/naev/.github/workflows/compile_naev.yml@main"
    with:
      platform: 'linux-latest'
      native_file: 'linux'
      build_type: 'debug'
      wrap_mode: 'forcefallback'
      nightly: false
      lto: 'enabled'
      auto_features: 'enabled'
      c_docs: 'disabled'
      lua_docs: 'disabled'
      appimage: true
  "Linux_LTS":
    uses: "projectsynchro/naev/.github/workflows/compile_naev.yml@main"
    with:
      platform: 'linux-lts'
      native_file: 'linux'
      build_type: 'debug'
      wrap_mode: 'forcefallback'
      nightly: false
      lto: 'enabled'
      auto_features: 'enabled'
      c_docs: 'disabled'
      lua_docs: 'disabled'
      appimage: true
  "Steam_Runtime":
    uses: "projectsynchro/naev/.github/workflows/compile_naev.yml@main"
    with:
      platform: 'steamruntime'
      native_file: 'linux_steamruntime'
      build_type: 'debug'
      wrap_mode: 'forcefallback'
      nightly: false
      lto: 'enabled'
      auto_features: 'enabled'
      c_docs: 'disabled'
      lua_docs: 'disabled'
  "Windows":
    uses: "projectsynchro/naev/.github/workflows/compile_naev.yml@main"
    with:
      platform: 'windows'
      cross_file: 'windows_cross_mingw'
      build_type: 'debug'
      wrap_mode: 'forcefallback'
      nightly: false
      lto: 'enabled'
      auto_features: 'enabled'
      c_docs: 'disabled'
      lua_docs: 'disabled'
  "Darwin":
    uses: "projectsynchro/naev/.github/workflows/compile_naev.yml@main"
    with:
      platform: 'macos'
      cross_file: 'macos_cross_osxcross'
      build_type: 'debug'
      wrap_mode: 'forcefallback'
      nightly: false
      lto: 'enabled'
      auto_features: 'enabled'
      c_docs: 'disabled'
      lua_docs: 'disabled'
  "Documentation":
    uses: "projectsynchro/naev/.github/workflows/compile_naev.yml@main"
    needs: [ 'Linux_Latest', 'Linux_LTS', 'Steam_Runtime', 'Windows', 'Darwin' ]
    with:
      platform: 'docs'
      nightly: false
      lua_docs: 'enabled'
      executable: 'disabled'
      compile: true
      install: false
  "Website_Update":
    runs-on: ubuntu-latest
    needs: "Documentation"
    if: ${{ github.event_name == 'push' && github.repository == 'naev/naev' }}
    steps:
      - name: Trigger API Documentation Update
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: 'naev'
          repo: 'naev.github.io'
          github_token: ${{ secrets.WEBSITE_ACCESS_TOKEN }}
          workflow_file_name: 'website_publish.yml'
          inputs: '{ "publish_type": "api" }'
